### ISSUE TITLE
.git Ignore Installer Folder on Windows?

### ISSUE THREAD

**Issue by cochese9000** [C0untFloyd/roop-unleashed#165]
At the moment, the install process adds thousands of files to the git repo, due to them being installed under the installer folder..

**Comment by cochese9000** [comment]
Wierd, my install is working, but I followed the instructions on the readme and I think they might be wrong.

I have a git cloend repo for roop-unleashed, then, in my installer folder, I have ANOTHER roop-unleashed git clone, which is where the installer has put the models (again).  I already downloaded all the assets/models by doing pip install -r requirements.txt.  

Is this a bug, doc issue or just me?  I can't tell.  It might be the cause of the above (guessing so).

**Comment by C0untFloyd** [comment]
Do I get you right, you cloned the repo yourself and executed the installer from the cloned folder afterwards?
If so, it isn't meant to be done like that and yes, then you have the installation inside the other stuff.
Instead you should just download the zip with the installer https://github.com/C0untFloyd/roop-unleashed/releases/download/v2.7.0/roop-unleashed_win_v2.7.0.zip, unzip it and run the installer from there. It does all the downloading and cloning for you.
Oh and after installing you should do another update round, because the installer is fixed to the release commit and doesn't download the latest source (user request).

**Comment by cochese9000** [comment]
@C0untFloyd ah, I see.  I just re-read the install instrcutions and realised I was using the 'other OS' one, not the 'just use installer' one.  Not sure why I did that.  Think I just missed it, but posslby because i'm already using Conda and thought that might work.
