### ISSUE TITLE
[Dev Branch] Some swapped videos freeze at random

### ISSUE THREAD

**Issue by Lordmau5** [C0untFloyd/roop-unleashed#199]
**Describe the bug**
So I've seen the dev branch got a few nice changes (Loving the reworked UI 😁) and I gave it a try with some video face replacement.

However, it seems that some videos stop having frames added at some point (as in, they freeze) but the audio keeps going.

I tried it with a couple of videos - on some it happens, on others it doesn't.

I linked a video further below where it did happen on, but **only** if I set a start and end frame.
Maybe something to do with keyframes?

**To Reproduce**
1. Load a source face
2. Load a video and detect a face in it
3. Set start and end frames
4. Start the swapping process
5. Find out that the video stops at some point

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
2.9.5 (Latest commit from the dev branch)

**Screenshots**
Source video: 

https://github.com/C0untFloyd/roop-unleashed/assets/1345036/30e86421-dfd0-4d77-bfb7-88fe7a329dee

Resulting video (Frame range 135-572):

https://github.com/C0untFloyd/roop-unleashed/assets/1345036/299e2f54-798f-4490-84b0-107e6672584b

**Comment by Lordmau5** [comment]
Heh, yeah I thought giving the dev branch a try wouldn't hurt, that way if there are any issues you could iron them out before merging it into main 😉 

And no, it doesn't seem like GitHub is re-encoding them. I downloaded one of them and did a SHA-256 hash check against my local file, they are identical

As for ffmpeg, I got `6.0-full_build-www.gyan.dev` installed through Winget

**Comment by C0untFloyd** [comment]
Ok I fixed it but it puzzles me. Using your example video with start 135, end 572:

* In-Memory created a frame exact video with 437 frames
* Extracting frames using ffmpeg creates 572 frames! Actually the very first frame nr. 135 is extracted for 135 times.

After restoring audio, in-memory video was either freezing or even corrupt. Extracted video was correct and frame number shrunk to the correct number of 437. I'm now doing the same manually with the in-memory method and it is working. I need to avoid doing this when audio is skipped though, otherwise the extra frames wouldn't disappear in the final video. And I just can't think of a reason why that is in first place. For a big video this might mean writing the same frame a million times...can't believe this is really needed.

**Comment by Lordmau5** [comment]
The only first thought I had would've been that it has something to do with keyframes, seeing as it works fine if you do the whole video without start and end...

So maybe it's something that can be done in the ffmpeg arguments to fix it?

**Comment by C0untFloyd** [comment]
This was finally resolved: ffmpeg needs an additional argument `vsync 0`
😫
