### ISSUE TITLE
Pixalate result-bad quality

### ISSUE THREAD

**Issue by gunjahman** [C0untFloyd/roop-unleashed#2]
The script works perfectly, but it lacks quality. No matter how big the size or resolution has the source image when it is applied to the target image, it has many pixels and very bad quality. (the issue is just for the swapped face, the rest of the target image keeps the original quality)
Am I doing something wrong, or does the script needs improvement?

**Comment by C0untFloyd** [comment]
No to both 😝 
The problem is the trained network model from insightface which only uses a resolution of 128x128 pixels. They also have a model trained for 512x512 but they got greedy sometime and their model can only be used in a private discord from them. So the solution currently is to use the post-enhance toggle option. You need to add face-enhance to your commandline arguments too e.g. `set COMMANDLINE_ARGS=--execution-provider cuda --frame-processor face_swapper face_enhancer --video-encoder libvpx-vp9`

**Comment by lost-in-emotions** [comment]
sorry for warmup: where do i insert the command line?
**`set COMMANDLINE_ARGS=--execution-provider cuda --frame-processor face_swapper face_enhancer --video-encoder libvpx-vp9`**

some .bat with edit? and wich line? 
thanks for help :-)

**Comment by C0untFloyd** [comment]
This is not needed anymore, you just need to select the type of enhancement you want in the UI Combobox:
https://github.com/C0untFloyd/roop-unleashed/wiki/Face-Swap-Tab#face-swapping-parameters-enhancement-options-and-masking

**Comment by lost-in-emotions** [comment]
ok, but i do it already. whats the cause, when my faceswap is very blurry and pixelated? on images when the person is more in the backgroun (cowboy-shot), it works good, but when its a portrait f.e. in  1000px x 1000px it looks really bad :-( or is this caused by my source image?

**Comment by C0untFloyd** [comment]
I don't really know without seeing your images but if your input images are lo-res it won't work well of course and the max resolution of the enhancers is 512x512.  There is no upscaling if that's what you're looking for!
