### ISSUE TITLE
Frame Number slider doesn't show the correct frame in the preview

### ISSUE THREAD

**Issue by Niiickel** [C0untFloyd/roop-unleashed#214]
**Describe the bug**
Frame Number slider doesn't show the correct frame in the preview.
When I refresh after using the slider, the right frame is shown.
Is this intended? Cause having to slide quickly between frames was my go-to workflow in earlier versions.

But I have this problem since a few releases, so the problem shouldn't be the new version

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**

3.0.5

**Comment by C0untFloyd** [comment]
From what I've seen it's the other way around: the slider doesn't work correctly but the arrows do. The reason is the gradio UI again, the change event of the slider is called while the previous event isn't even finished. I added a delay of 0.2 secs but this didn't seem to change anything. I will try bugging the gradio devs again. In the meantime you could use the slider to do big steps and afterwards just click 1 time on one of the arrows.

**Comment by lysxelapsed** [comment]
The gradio devs must love you by now 😅 
I think 0.2 secs delay might not be enough. Have you tried a higher value?

But: Since the process will always have the "extra step" (the browser / gradio), I recommend using a video player for picking out a suitable frame anyway. My go-to is MPC-HC for this, great little player. Frame-by-frame-steps with ctrl+arrows, shows current frame number with ctrl+g. For videos I might use more than once, I just save the filename and frame number in a textfile.

**Comment by Niiickel** [comment]
> From what I've seen it's the other way around: the slider doesn't work correctly but the arrows do. The reason is the gradio UI again, the change event of the slider is called while the previous event isn't even finished. I added a delay of 0.2 secs but this didn't seem to change anything. I will try bugging the gradio devs again. In the meantime you could use the slider to do big steps and afterwards just click 1 time on one of the arrows.

Did you change anything? The problem seems to be fixed for me.
If so... many thanks!

**Comment by C0untFloyd** [comment]
Closing this as there's currently nothing I can do.
