### ISSUE TITLE
 Is there any way to directly replace the target person’s mask?

### ISSUE THREAD

**Issue by newlife0007** [C0untFloyd/roop-unleashed#242]
Is there any way to directly replace the target person’s mask?
When I replace the target character with the mask, the mask part vaguely has the src character's face. Are there any parameters that can be adjusted to directly output the face of the src character without masking?

**Comment by C0untFloyd** [comment]
I was hoping someone else tries to help you because I'm not sure I understand 😃 
What do you mean with directly output? Is it about the likeness of the face? The swapper used by roop unleashed does deepfakes with just a single photo and no training. The results are pretty good for that but for professional fakes I guess you would need to use tools which can be trained like [Deepfacelab](https://github.com/iperov/DeepFaceLab).

**Comment by newlife0007** [comment]
Sorry, maybe I didn't express myself very clearly. I uploaded an example image. As a result, the face of the source character in the picture has actually been replaced, but it is not fully displayed.
![7_3](https://github.com/C0untFloyd/roop-unleashed/assets/62409302/20d81edf-6397-417b-88bb-a0e42603a36b)
![1](https://github.com/C0untFloyd/roop-unleashed/assets/62409302/60214d56-c13b-4664-b165-e26c88df96dc)
![3](https://github.com/C0untFloyd/roop-unleashed/assets/62409302/fba15c19-9e52-4027-b183-69cb488c48e6)

**Comment by C0untFloyd** [comment]
Oh you're talking about an actual face mask! Well, the face swapper tries to do its best to blend the faked face into the existing, so it will also try to mix it with the face mask, there's no workaround for this. What you can try however is using the text masking to have the original face mask cover the lower face again. That should definitely work but would of course cover the deepfake like the original face.

**Comment by newlife0007** [comment]
For text masking. I don't know how to fill in the keywords to achieve the effect of removing the face mask. Are there any examples? Or fill in the original face?
I had filled in some words, but after previewing them, I had no idea what purpose it served.

**Comment by C0untFloyd** [comment]
You would need to name the object you would like to restore in the final image. Tried it with your example:

![mask](https://github.com/C0untFloyd/roop-unleashed/assets/131583554/2b41ab97-b452-460c-b0fc-1d71f4d0c44e)

As you can see it masks the mask from the original image 😃 
To my surprise it wasn't working in the final swap, the faked mouth is still shining through. I think you found a bug and I need to look into it.

**Comment by C0untFloyd** [comment]
Ok found the problem: the mask gets detected when processing the complete image in the preview, but it's not detected on the cutout face. Seems like for these special cases an additional mode is needed to process the whole image instead of the face cutout only.

**Comment by C0untFloyd** [comment]
Rewrote the masking to process the whole image, please update to the newest version. This should enable better detection but also masking in places which aren't even used and I don't really know about performance then.
Anyway here is the result:
![masked](https://github.com/C0untFloyd/roop-unleashed/assets/131583554/2fbde500-9355-4b2f-8102-cd1849e3d82d)

As you can see it's suboptimal because the mask includes parts of the face, this affects the right eye which looks weird. But for the moment this is as good as it gets, perhaps the future masking methods I want to implement will create better masks.

**Comment by newlife0007** [comment]
Thanks for the changes, this is much better.
However, I feel like my description still didn't clear my expectations.
I expect that the mask will not show up in the final face result.
Like the example picture below (the example picture is made by PS😅)
![11](https://github.com/C0untFloyd/roop-unleashed/assets/62409302/ddd51246-2775-4e1c-9f01-08c444b30301)

**Comment by C0untFloyd** [comment]
No this is just not possible with the current model, it will always try to to blend into the original face (which in this case is just a face mask). You could however swap into your crude photoshopped face or use stable diffusion inpainting. Best would probably really be to inpaint away the face mask and then do a normal face swap.
