### ISSUE TITLE
Explaining the previous issue in detail, "SELECTED FACE OPTION NOT WORKING PROPERLY FOR ME"

### ISSUE THREAD

**Issue by inane-mafia** [C0untFloyd/roop-unleashed#264]
**Describe the bug**

 👇🏻

⚠️**As we can clearly see that i selected the "3rd target face" and clicked on "use selected face and done"
still in the final output, the face replaced is of the 1st girl, which i didn't even select**

more detail- source img is 1164 x 1386 pixels  (1.3mb) and target img is 1300 x 866 pixels (200 kb)

when the image / video contain more than one person, i select the "selected face option"
most of the times it doesn't work, the 1st found face is always the priority

*IN VIDEO, if there are more than 1 female, the face is swapped only for the first person and stays on her, 
                  if there is a male and a female , there is a 50/50 chance that the face swap will keep switching between the target and 1st 
                  face

**To Reproduce**
1. Click on 'use face form this frame'
2. Click on 'selected face'
3. ⚠️ Click on the 2nd or 3rd face
4. Click on "use selected face and done"
5. Click on "start"
6. the output has  the 1st face swapped INSTEAD OF 3RD

**Details**
What OS are you using?

-  Windows 11

Are you using a GPU?
-  No, CPU - ryzen 

**Which version of roop unleashed are you using?**
latest 3.1.1

1. INSERTING BOTH THE IMAGES
![Screenshot 2023-10-01 161700](https://github.com/C0untFloyd/roop-unleashed/assets/145937224/345438e0-4ab9-4bf7-b7aa-9cf7ef9b829c)

2. CLICKED ON "USE FACE FROM THIS FRAME"
![Screenshot 2023-10-01 161725](https://github.com/C0untFloyd/roop-unleashed/assets/145937224/5bd37493-ba63-4c41-bcdc-2b065b03e7b4)

3. ⚠️ **SELECTING THE 3RD FACE**  + USE SELECTED FACE + DONE
![Screenshot 2023-10-01 161741](https://github.com/C0untFloyd/roop-unleashed/assets/145937224/0ce48c85-6976-4ed0-8361-cee7611f30c5)

4. ⚠️ THE 3RD IMAGE IS SELECTED (VISIBLE ON TOP)
![Screenshot 2023-10-01 161802](https://github.com/C0untFloyd/roop-unleashed/assets/145937224/eb9524b2-9174-466a-9323-8ee0b4858bea)

5. ⚠️ CLICKED ON SELECTED FACE OPTION
![Screenshot 2023-10-01 161814](https://github.com/C0untFloyd/roop-unleashed/assets/145937224/bb210e14-7b6c-48f3-9a1e-4e29efc8b18a)

6. IN THE OUTPUT, THE 1ST FACE IS SWAPPED INSTEAD OF 3RD
![Screenshot 2023-10-01 161836](https://github.com/C0untFloyd/roop-unleashed/assets/145937224/830ee3ca-1eff-47f8-abd0-6a7b03c4fabe)

⚠️I HAVE USED MOST OF THE PREVIOUS VERSIONS

BUT, THIS PROBLEM STARTED SOMEWHERE AFTER 2.7 VERSION
AND I FACED THIS PROBLEM EVEN IN GOOGLE COLLAB 2.7, 2.8 ..... 3.1

is the bigger size of source face the problem? 
i tend to upscale source faces on waifu 2x website (around 1200 x 900 pixels)

**Comment by C0untFloyd** [comment]
Ok, I now understand the issue. I never encountered that problem, tried with your screenshot:

**Screenshot** 
![screenshot](https://github.com/C0untFloyd/roop-unleashed/assets/131583554/e1cec1f6-265a-406b-98b3-a2ceac971db8)

**Result**
![Result](https://github.com/C0untFloyd/roop-unleashed/assets/131583554/95f69f22-5fd3-473d-ac82-74318dfad546)

While doing this I noticed the faces of the first 3 girls are very similar (are they twin sisters or something?).  I would have a hard time telling them apart, especially 2 & 3. Perhaps their biometrics (eye distances etc.) are also very similar. This could explain the weird behaviour because if 1 girl is facing to the side and another very similar face is looking towards the camera, the calculated distance will be closer to the wrong one. I *think* you should try lowering the face similarity value to perhaps 0.5 or even less to make the calculation more strict. Just be aware that this perhaps leads to face flickering as the face isn't even seen as similar anymore at weird angles.

**Comment by wgalunw** [comment]
Right now, I am unable to use the live cam feature; my OBS is completely black. I would like to ask for your help in troubleshooting this issue.
![Screenshot 2023-10-02 124605](https://github.com/C0untFloyd/roop-unleashed/assets/143527151/0f7fbd82-a806-4b2c-a9e9-409991f47d2d)
![Screenshot 2023-10-02 124428](https://github.com/C0untFloyd/roop-unleashed/assets/143527151/b55b2adc-5402-4d39-a965-b1940bafe7ee)
![Screenshot 2023-10-02 124913](https://github.com/C0untFloyd/roop-unleashed/assets/143527151/f9d4b618-ddc5-402e-92f0-7f5f2da1ccd2)

**Comment by inane-mafia** [comment]
thanks, i think keeping the face similarity at max was the problem, 0.5- 0.6 is working fine for me now
