### ISSUE TITLE
Hardware Acceleration on MacOS (Intel) x86

### ISSUE THREAD

**Issue by u3214vf590dc** [C0untFloyd/roop-unleashed#306]
**Describe the bug**
Unable to get HW acceleration on macOS Intel (x86). I am using an eGPU (amd). 

**To Reproduce**
Installed using pip. App works fine with cpu as execution provider. 

I followed the HW Acceleration Instructions for Apple Legacy (pip uninstall onnxruntime onnxruntime-coreml pip install onnxruntime-coreml==1.13.1). App no longer runs (wrong architecture error). 

Seems like the coreml pip install doesn't support x86. How do I get onnxruntime to use CoreML EP on macOS x86?

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [X ] Mac

Are you using a GPU? (>> I am trying to)
- [ ] No. CPU FTW
- [ ] NVIDIA
- [X ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**

**Screenshots**

**Comment by phineas-pta** [comment]
u cant

**Comment by u3214vf590dc** [comment]
Thanks for replying. Could you elaborate? Why is it not possible? Are you saying the instructions page in the project is wrong?

If it is not possible, what is the easiest way to get HW acceleration? I have a Mac mini 2018 with an AMD eGPU.

**Comment by phineas-pta** [comment]
unfortunately non M mac can only use cpu

**Comment by u3214vf590dc** [comment]
Thanks. Two more questions. 

1. Can I get hardware acceleration on an M1 Mac (if so, how?)

2. If I boot the intel Mac in windows and use NVidia GPU, will I get hardware acceleration?

**Comment by phineas-pta** [comment]
mac in any kind isnt suitable for AI workload

if u just to play around pay for colab

if u seriously interested buy pc eith nvidia

**Comment by u3214vf590dc** [comment]
Thanks. One more question 

Will the ROCm Executioner work in Linux with an AMD Vega 64?

**Comment by phineas-pta** [comment]
yes if u know how to build from source

**Comment by Oil3** [comment]
Have a read there https://onnxruntime.ai/docs/execution-providers/ROCm-ExecutionProvider.html
If you use the egpu, I dont think you can use metal?
Im searching for a thunderbolt cable and will soon be asking myself the same questions to try my mini +amd on egpu).
for your other question, it works good on M1, it works very good.

**Comment by Oil3** [comment]
@u3214vf590dc 
it's very possible. I think it's something silly that makes onnxruntime with CoreML to only use the CPU. It's CPU but hardware accelerated. God willing I or someone will figure out how to unlock onnxruntime and make it use all computing units with coreml execution provider. 

Meanwhile, I did compile onnxruntime on my old intel mac mini, and it is using coreML. 
it required no tinkering to build it, and it built without any error and with 100% tests success.
![Screenshot 2023-12-14 at 4 48 25 AM](https://github.com/C0untFloyd/roop-unleashed/assets/22565084/77656ffd-961e-4438-91ff-37cea52da185)

https://github.com/Oil3/onnxruntime-mac

download the .whl file and then pip install it after having uninstalled the other onnxruntime packages
```

pip uninstall onnxruntime
pip uninstal onnxruntime-silicon
pip install /pathTothefile/onnxruntime-1.17.0-cp39-cp39-macosx_14_0_universal2.whl

```

**Comment by Oil3** [comment]
@u3214vf590dc It's very possible! my mini wih radeon rx 580 is kinda running on tenserflow (just did a test)k and on onnxruntime, immediate integrated intel gpu kicked in.
for both they run 20ish% max.
![Screenshot 2024-01-03 at 00 54 58](https://github.com/C0untFloyd/roop-unleashed/assets/22565084/82b05bd4-46ec-49c9-a7f2-154c7c1a72c5)
![ss 2024-01-03 at 3 21 31 AM](https://github.com/C0untFloyd/roop-unleashed/assets/22565084/03e2c7ad-1a38-4dfa-9d95-6040e44100c3)
![ss 2024-01-03 at 3 17 14 AM](https://github.com/C0untFloyd/roop-unleashed/assets/22565084/9c9afded-71b7-4cb0-bde2-d00b15f05f11)
![ss 2024-01-03 at 2 41 33 AM](https://github.com/C0untFloyd/roop-unleashed/assets/22565084/33a5873a-d8b9-4ba9-b9fe-12f02968afc0)

I need a cable and am running the egpu with the usb c cable from a lg monitor (thin
Those machine are still powerful! 
Geekbench metal benchmark is higher than silicon M2, and half the M1max.
It runs using Metal performance shaders, I'm confident their literal silicon ban will be lifter, surely once Apple gets his share of the ML/"AI". e
Just need the onnxruntimes with coreml, you'll have to build it, or [use the one i uploaded](https://github.com/Oil3/onnxruntime-mac/blob/main/onnxruntime-1.17.0-cp39-cp39-macosx_14_0_universal2.whl) but its only for pyrhon 3.9.
Building bunch of errors, it's a real mess, @Cansik has a [good solution, just need to run it,](https://github.com/cansik/onnxruntime-silicon) arm64 packages even labelled universal are no-no.
Also just saw this pull request with information of interest https://github.com/cansik/onnxruntime-silicon/pull/15
Iv had issues caused by those "venv" "conda" and it's been complicated on the mini, those things are nonsence, and use lots of space, homebrew and pip never had issues that werent fixed the same day.
*
I think we should focus on pytorch, tensorflow and coreml.
Oh by the way, did yoy know onnxruntime just converts the onnx model into multiple coreml models and  thats it? The models convertion has cpu only as mlcompute, and is using years old coremltools library.
Also, [everything is already there ](https://github.com/oil3/onnxruntime-mac)to: convert within the onnx model int32 to int64 (coreml doesnt like int64, onnx runs on int64), convert the model to mlmodel on the fly, to name a few...

**Comment by Oil3** [comment]
As a FYI, thats the way it works: onnx uses coremltools (an old version,  its a bit sad, like 3 years old...), makes a coreml model, compiles it, all this by dividing the model in smaller models.

To leverage GPU, have to change every "bicubic" or "cubic" to linear or bilinear, and maybe also change every mention of "cpu only" flags, en particular for the model creation, so that it can"t be applied:
What determines what's used is how the model is configured, and you can set preferences.

On silicon, without enhancer:
![ss 2024-01-17 at 7 06 57 PM](https://github.com/C0untFloyd/roop-unleashed/assets/22565084/534d4fe7-6885-43f8-910d-9a5bddd28e98)
