### ISSUE TITLE
real-time preview of video files?

### ISSUE THREAD

**Issue by Mimicvat** [C0untFloyd/roop-unleashed#333]
Hi, from what I've seen it's possible to use the webcam and change the face in real time, but I'd like to know if it's possible to have a real-time preview of video files? 

My 3070ti sometimes can't deliver much fps in high quality videos with GPEN and I'd like to see a snippet of the video before I start doing the whole process. 

I know I can select a snippet of the video between times X and Y, but sometimes it's not enough and the process of converting and saving videos gets tedious if we have a lot of faces to change. 

It would also be interesting to have a frame skipping option to show in real time, reducing the number of frames in the original video, e.g. a 60fps video of 5 minutes has around 18000 frames, there could be an option to skip 1/3 of the frames and have 6000 frames.

**Comment by alast0r** [comment]
just do like 200 frames maybe? get the newest master you can select the frames

**Comment by Oil3** [comment]
I can't get the real time preview, but I found a way to see _a _snippet_  by using the ffmpeg fasttrack thing, creating a playable video if I stop the process before it finishes.
Instead of having a broken mp4, its playable, but you have to _stop_ the process, it doesn't work for me if I copy the file while the faceswapping is in progress.

in **roop/ffmpeg_writer.py** insert at line 130
`# move mandatory metadata to begining of video so it can play before being finished
        cmd.extend([
            '-movflags', '+faststart',

        ])     `

**Comment by Mimicvat** [comment]
Just found that [https://github.com/Hillobar/Rope](https://github.com/Hillobar/Rope) have a real-time video player, seems like a good start.
