### ISSUE TITLE
Process slowed down for no reason

### ISSUE THREAD

**Issue by Shaaaaaaaw** [C0untFloyd/roop-unleashed#334]
Hi,

At the begining everything is ok. But after 1 or 2 successful processings, the process will be abnormally long... 
For example, the first processing will take 10 seconds, litteraly. But then, it will take 5-10 min (for the same video).

And after a few moments it becomes normal again.

I don't know why.

**Comment by lysxelapsed** [comment]
How many threads are you running and with which enhancer? Check your VRAM (GPU Memory) usage. A sudden and significant performance drop in the middle of processing, is usually related to exhausting all of your VRAM, as a result of running too many threads. See my post in #320 for details.

Side-note: I've noticed that the VRAM usage can vary even in running a single video. When the swapping process is skipping frames due to no faces being detected, VRAM usage _can_ go up (I'd say up to 10%) when it re-engages in the swapping process.
I made it a rule, when trying new settings or enhancers, to have at least a VRAM reserve of 2GB (RTX3060, 12GB) for this phenomenon and other processes. When I see that the new settings / enhancer use more than 10GB VRAM, I cancel the process immediately and start again with thread count lowered by one, rinse and repeat until initial VRAM usage is below 10GB again.

I'd start with watching the VRAM usage during processing and (probably) a lower thread count. Once you've exhausted all of your VRAM and the performance drops, closing / restarting roop-unleashed is your only simple option to free the VRAM up again. At least as far as I know.

**Comment by Shaaaaaaaw** [comment]
Hello,

I use between 10 and 12 threads with an RTX 3090. So this uses around 22/23 VRAM out of 24. And actually the only way to counter this latency is to restart roop.

I'll try to reduce my thread...

**Comment by lysxelapsed** [comment]
Yes I'd recommend a bit more VRAM reserve. As you can see in the pic, there's an initial spike in VRAM usage when it's loading / initializing the model.
First part is idle after processing a video
Second part is loading a new source pic (first spike, loading / initializing model, single preview swap)
Third part is trying another source pic (second, only small spike since the model is already loaded, single preview swap)
Last and biggest spike (somewhere around 11GB VRAM) is at the start of the swapping process, before it goes down to 9GB.
If that peak at the start (don't get fooled by the first video, which peaks maybe at 10GB instead of the 11GB for 2nd, 3rd etc. in my case) goes over my available 12GB -> game over, poor performance 😆 
![roop spike](https://github.com/C0untFloyd/roop-unleashed/assets/63816546/4fe89de1-8627-4904-96b3-742fbf577789)
