### ISSUE TITLE
UI not showing up DirectML as option for AMD GPU 

### ISSUE THREAD

**Issue by limeyslimey** [C0untFloyd/roop-unleashed#348]
**Describe the bug**
As mentioned in [this ](https://github.com/C0untFloyd/roop-unleashed/issues/339) issue that Direct ML will show up as a selection in providers, but I'm not able to find that option, despite following the instructions. 

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [*] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [*] AMD
- [ ] Intel
- [ ] Mac

CPU: 5800H
GPU: AMD Radeon RX 6600M
GPU Driver: 23.11.1

Environment: python: 3.10.13 • torch: 2.0.1+cu118 • gradio: 3.44.2
roop unleashed 3.3.4

**Comment by lysxelapsed** [comment]
Aside from the [wiki](https://github.com/C0untFloyd/roop-unleashed/wiki) and what I already mentioned in #339, here's what to look at: https://onnxruntime.ai/docs/execution-providers/DirectML-ExecutionProvider.html / https://onnxruntime.ai/docs/install/#cccwinml-installs

Also you could ask @kevin2509-dev via DM, what the issue was in his case, since he didn't post it.

**Comment by limeyslimey** [comment]
I feel if @kevin2509-dev can answer here, it could also benefit others. Can you please help us out here?

**Comment by Oil3** [comment]
I remember I had to do a bunch of things in  order to get my MPS device to show up, that included instaling and reinstalling stuff from the requirements.txt and not necessarly the versions stated.
Do you have everything?
wbat's your onnx version?

**Comment by Moilamar** [comment]
It works for me only when running `python run.py` instead of the exe file.
