### ISSUE TITLE
Add support for CLI . Colab is not letting use the server to host the webui. CLI is the only Way.

### ISSUE THREAD

**Issue by tikendraw** [C0untFloyd/roop-unleashed#372]
** Problem**
Colab is not letting to host the webui. 

** Solution**
Add cli args to main run.py
if no args are passed then run webui else use cli.

**To Reproduce**
Try to run this in colab.

What OS are you using?
- [X] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW 😅😅😅😅😅
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac
- [x] Whatever GPU Colab has for free tier

**Which version of roop unleashed are you using?**
latest

**Screenshots**
don't have the screenshot. but it said free tier user can't use colab to allow me host or something (similar to that)

**Comment by Oil3** [comment]
It's against their terms of use to use faceswap things, even for paid.
What do you want to achieve with CLI?

**Comment by tikendraw** [comment]
> It's against their terms of use to use faceswap things, even for paid. What do you want to achieve with CLI?

Previously, I have done faceswap and it worked with no warnings.
So I thought it was a tunneling or hosting issue, that's why i requested for cli support.

**Comment by Oil3** [comment]
If they say don't do it, it(s better to respect their wishess, it's spot on the  "ethic issues"  of faceswap.
And I dont see how a ccku would solve your matter,  if u have remote access  for a command, you have remote access for the webserver?
I think you go too deep in your thinking, they just detected the soft as what it is: last week I wanted tio t ry tha colab thing, had a very india academic high IQ vibe with a loi of explanation, probablt videos, and I was like _shiiiit just give me  a prompt_  then I understood I had a prompt where I wanted how I wantred with a little nice play button to run code, 
and I tried but this google popup said it was against their terms and I still wanted to run it.
I deleted/close/left.
SInce I never tried it,was  is it good? Fast?

**Comment by tikendraw** [comment]
I misunderstood the problem and requested a alternative solution. Other than that there is nothing to say. 

Also, WTF is this? 
> I think you go too deep in your thinking, they just detected the soft as what it is: last week I wanted tio t ry tha colab thing, had a very india academic high IQ vibe with a loi of explanation, probablt videos, and I was like _shiiiit just give me a prompt_ then I understood I had a prompt where I wanted how I wantred with a little nice play button to run code,
> and I tried but this google popup said it was against their terms and I still wanted to run it.
