### ISSUE TITLE
Launching Roop breaks windows file explorer

### ISSUE THREAD

**Issue by udkim1** [C0untFloyd/roop-unleashed#377]
Hi.
Everytime i open roop, after a couple of minutes, all the thumbnails in file explorer become the empty white symbol. if i then close the explorer window, the next time i open it, it is completely empty, with only the green bar loading forever. This only happens after i open Roop.

**Comment by C0untFloyd** [comment]
Yeah right.
You know, I believe you that this is happening but it just can't be caused by roop unleashed as the Python Rnvironment runs more or less in a sandbox environment and I know for sure I'm not doing magic windows stuff. Also this is the first time anyone is reporting this. Some ideas you might pursuit:
* Your PC RAM or GPU VRAM is out of memory
* Your GPU memory is partially damaged
* Your windows installation is corrupted
