### ISSUE TITLE
Processing speed really slow 

### ISSUE THREAD

**Issue by Clicli99** [C0untFloyd/roop-unleashed#383]
Hello C0untFloyd, I’ve got a issue: I always used DmdNet to process a video as it was the fastest (runtime shape always set on high ), everything worked relatively well until some days back, now it takes much longer to finish even a small clip. What’s up with the sudden speed-drop ?

**Comment by C0untFloyd** [comment]
That's a question you can only answer yourself. Does the current NVIDIA driver have issues, is your RAM faulty, did you copy roop from SSD to standard HD? There was no change in roop for quite some time.

**Comment by DietmarSchibrowski** [comment]
I encountered the same problem. No changes or updates on my hardware. Just roop suddenly taking extremely long for the same tasks as before...

**Comment by C0untFloyd** [comment]
The latest v3.5.5 should rather give you another ~ 5% speed increase. Did you read the section in the FAQ about VRAM? Over time with more and more models roop became increasingly memory hungry, perhaps that's the issue here.

**Comment by DietmarSchibrowski** [comment]
I'm using 3.5.3. Are you referring to running multiple processes immediately after one another? In a different thread I read about having to restart roop to clear the VRAM.

**Comment by lysxelapsed** [comment]
Definitely not something on the roop-unleashed side. Like already mentioned, there's even been a small speed increase in 3.5.5. But there's no reason why the speed on 3.5.3 or any other version should have decreased suddenly.
Most of the time, these issues are either related to exhausting either the RAM (though python will complain about that in the terminal window,) or (mostly) the VRAM (nothing but speed decrease in the terminal window)
If I'm using 3 threads instead of 2 for example (so is VRAM almost maxxed out), I have to be carefull to open too many other apps. Even a single explorer window can take up to 20MB of VRAM. With 2 threads I don't have to worry about that.
