### ISSUE TITLE
The processing speed has been very slow these last few days.

### ISSUE THREAD

**Issue by alejotomaz** [C0untFloyd/roop-unleashed#384]
**Describe the bug**

**To Reproduce**

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**

**Screenshots**

**Comment by Oil3** [comment]
Yes ok it's slower, but what? On your computer?
Is it since the last merge? XWhat did you do?
I don't mean it in a bad way, but from the level of detail of your post, it could be anything. 
Like you suddenly started using higher resolution data, or filled up your disk...
Me I found that package version s like onnxruntime or numpy or anyhing, can havean enormous impact on speed.

**Comment by C0untFloyd** [comment]
#383
