### ISSUE TITLE
insightface models "wrong" folder 

### ISSUE THREAD

**Issue by MajorXAML** [C0untFloyd/roop-unleashed#389]
**Describe the bug**
Hello,
I found that one model is downloaded to the system drive, when you first add a photo for face input, buffalo_l.zip is downloaded to `C:\Users\user\.insightface\models\buffalo_l.zip`

Is there any way to store it where all the other models are? i.e here: roop-unleashed/models/

**To Reproduce**
1 Delete buffalo_l folder in C:\Users\user\.insightface\models\
2 Launch windows_run.bat
3 Add photo

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [+] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [+] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
v3.2.0

**Comment by lysxelapsed** [comment]
Yes that's the default cache directory. [Here's](https://huggingface.co/docs/datasets/cache) how to change it.

**Comment by MajorXAML** [comment]
> Yes that's the default cache directory. [Here's](https://huggingface.co/docs/datasets/cache) how to change it.

Unfortunately the link you provided has nothing to do with this file

This seems to be a problem since the first roop https://github.com/s0md3v/sd-webui-roop/issues/108

**Comment by C0untFloyd** [comment]
You are both half wrong 😛 
@lysxelapsed showed how to change the default folder for python app data files. Changing it will of course also change the insightface subfolder in it.
Saying this is a problem...I don't know. That cache folder is the default for every python app. Automatic1111 started to make this more convenient to people by allowing the models etc. to be downloaded to its own subfolders. Somehow people then started to forget about the default caches. Anyway, the only minor problem is that insightface doesn't delete the zip file after downloading but this only happens the very first time. If you know your way around python code, you can integrate the buffalo model into my other regular model downloads and tweak the code some more to load it from there. I'd happily accept a PR which does it, I'm not doing it because its tedious and IMHO not really needed.
