### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by tomcoleman** [C0untFloyd/roop-unleashed#401]
Launching roop unleashed
Check for Updates? [y/n]n
Launching App
Traceback (most recent call last):
  File "C:\Users\thoma\Downloads\roop-unleashed-3.5.0\roop-unleashed-3.5.0\installer\roop-unleashed\run.py", line 3, in <module>
    from roop import core
  File "C:\Users\thoma\Downloads\roop-unleashed-3.5.0\roop-unleashed-3.5.0\installer\roop-unleashed\roop\core.py", line 14, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

Done!
Press any key to continue . . .

clean install running the windows_run.ba file get the above error?

**Comment by C0untFloyd** [comment]
Dependant on your system, a torch package should be installed:
```
torch==2.1.2+cu118; sys_platform != 'darwin'
torch==2.1.2; sys_platform == 'darwin'
```

Try updating (answering the above with y)

**Comment by strizer9** [comment]
@Schnubbirunkel @tomcoleman This issue is due to insightFace. You will see big error while updating/installing. 

Best way to fix this is to install Visual Studio C++. You can reinstall it with again, modify it by checking C++ and python development kit. 

I found the solution here - [Here](https://github.com/Gourieff/sd-webui-reactor?tab=readme-ov-file#troubleshooting)
