### ISSUE TITLE
Insight face model

### ISSUE THREAD

**Issue by whitebabyblackmarket** [C0untFloyd/roop-unleashed#411]
What a great project! Is there any alternative to the 128x resolution for the face model? I heard there was a better model you have to pay for with insight face but I’m hoping there is a 512x or better model we can use with this glorious program.

**Comment by C0untFloyd** [comment]
There are alternatives like the SimSwap, Ghost and several mutations which are running at a 512 resolution. Those however are in no way as capable in preserving the facial identity as the awesome model from insightface. Unfortunately insightface removed almost all traces of their inswapper model from the github project pages and are actively having it removed from forks and derieved projects.  That's why there's no community trained version for higher resolutions and I doubt this will happen in the near future. As a workaround roop unleashed contains several upscaler/image restorer which upscale the face up to 512x512.

**Comment by Kallamamran** [comment]
No matter what I di i can't seem to get any useful resolution of the outputs :/
