### ISSUE TITLE
VR videos, plans on integrating vrswap?

### ISSUE THREAD

**Issue by Oedipus7** [C0untFloyd/roop-unleashed#421]
I am a lil special so I couldn't install vrswap project https://github.com/g0kuvonlange/vrswap/tree/refactor  and get it to work. So, I was wondering if you can integrate it to your friendly version of roop?

Also, the VR mode option that is currently available, what does it do?

**Comment by C0untFloyd** [comment]
> Also, the VR mode option that is currently available, what does it do?

Swapping faces on stereo videos/images like the vr ones, meaning this already works for undistored vr stuff.
That issue is already issued in #374

**Comment by C0untFloyd** [comment]
If there is only 1 face you want to swap you can of course apply face swap to everything, there is no difference. But if you want to swap a selected one from a group of people it wouldn't have worked, because the swapper would have stopped after finding the first occurance of the face. The VR Mode searches for the same face twice. 
Btw. do you have extra chromosomes? If yes, I know the other forum you were asking 😜
