### ISSUE TITLE
GPU Not being utilized on M2 Max on MacOS

### ISSUE THREAD

**Issue by robgreenberg3** [C0untFloyd/roop-unleashed#423]
I am trying to run and utilize my GPUs on device, but can't find the setting to change to enable the GPU to help with the rendering.

My Machine:
MacOS, M2 Max 12core CPU, 38 core GPU

To Reproduce

Just run roop-unleashed via terminal - run.py
Can't find the setting to enable gpu (I installed onnxruntime-gpu, but that itself didn't seem to help speed up rendering).

Details
What OS are you using?

 Linux
 Linux in WSL
 Windows
[x]  Mac
Are you using a GPU?
No, but I want to use the native GPU on my m2 max.
 NVIDIA
 AMD
 Intel
 Mac
[ x] System CPU

Which version of roop unleashed are you using?
3.5.0

Screenshots

**Comment by Oil3** [comment]
@robgreenberg3 i had a lot to say but i digressed so much ill cut & paste eleswhere.
key points:
onnxruntime-gpu is for nvidia
mac uses coreml runtime provider
it is very possible
![ss 2024-02-03 at 8 19 00 AM](https://github.com/C0untFloyd/roop-unleashed/assets/22565084/a75aeeb3-3e4e-4837-b695-6138984ef8da)


**, you need onnxruntime-silicon, if dont want to build youself (just need patience and a coreml  flag):**
I recommend get it from @cansik https://github.com/cansik/onnxruntime-silicon
or my version https://github.com/Oil3/onnxruntime-mac

so:
pip3 uninstall onnxruntime-gpu
pip3 install pathtothedownloadedfpackagewithoutchanginitsfilename

CoreML /MPS provider

let us know

fyy in the big text I chose not to post here, I give my opinion/experience on why it's so... ..... ... to be able to use all our mac computing units.
Taking into account that using coreml excution provider will have Onnxruntime convert on the fly and underthe hood the onnx model into a coreml model using a 4 years old coremltools version.

**Comment by R3D347HR4Y** [comment]
Same issue, did pip install onnxruntime-silicon and I think the render time went down a little but I still am not using the GPU at all whereas all CPU cores (performance and efficiency are all at 100% utilization)
Would love to know what settings / mods would make this process faster on Apple Silicon macs, it currently takes around 10 minutes to face swap a 10 second tiktok video at 30FPS with GFPGAN on my machine and my memory usage is not very high

Apple MBP 14 M3 Pro 36GB CPU 11C GPU 14C
MacOS Sonoma 14.1.1

![Capture d’écran 2024-03-03 à 15 00 17](https://github.com/C0untFloyd/roop-unleashed/assets/28823392/7fb5cecf-8966-43b4-b035-12eff57e5e73)

**Comment by Oil3** [comment]
modify ...../processors/Enhance_DMDNet.py
at line 197 you specify this `map_location="mps"` like that:  
`weights = torch.load('./models/DMDNet.pth', map_location="mps") 
`
And then that's it, on my M1max it goes 3 times faster with the GPU with MDnet instead of GFPGAN


@R3D347HR4Y nice machine man!
(Out of context: upgrade your OS above 14.1.1, there is a webkit 0day bad stuff)
it should take less than 10 minutes though, u up to date on other stuff like numpy and other?

THank you for your omment, I realized something. 

just do: 
> 
> modify ...../processors/Enhance_DMDNet.py
> at line 197 or something, where it loads the model, you specify this `map_location="mps"` like that:  
> `weights = torch.load('./models/DMDNet.pth', map_location="mps") 
> `
same for other pytorch models. DMDnet's interpolations are already set to bilinear so it's just one line.
the terminal built-in tool i used for power consumption is powermetrics.
it seems 25ish watts on battery and 30ish watts plugged. 
for textmasking/clip2set, replace all interpolations `BICUBIC` to `BILINEAR` and that's ernough, in all the files inside `CLIP`

  
![ss 2024-03-06 at 1 22 39 AM](https://github.com/C0untFloyd/roop-unleashed/assets/22565084/d49fe1d3-4681-42d2-b302-8730173fa445)
120seconds with gpfgan, gpu was at 0% however significant ANE consumption.  
`40` seconds with dmdnet with `map_location="mps"` CPU maxed, GPU nearly maxed, and  little ANE consumptions.

**Comment by R3D347HR4Y** [comment]
> mps

Alright so I updated to the latest version of OSX, and I replaced BICUBIC to BILINEAR in every file insde the "clip" folder, I also specified map_location="mps" in  torch.load in DMDNet and some other file I think.
It now only takes around 1 minute for a 10 second clip with DMDNet and about 2-3 minutes with GFPGAN
I think GFPGAN yields better results, would be cool to get MPS acceleration for this algo as well
Anyways, thank you very much, here's a quick vid of me testing it out now

https://github.com/C0untFloyd/roop-unleashed/assets/28823392/faffd6d2-33c0-46c5-a6f6-fe756319136f

**Comment by yuriwa** [comment]
I'm running version 3.5.5 and having the same issue (GPU is not utilised) even after following all of the steps in this thread.
