### ISSUE TITLE
AMD Windows

### ISSUE THREAD

**Issue by samrluxford** [C0untFloyd/roop-unleashed#456]
Look I know this is probably a dumb question because I haven't seen anyone else ask it but where am I putting
`pip uninstall onnxruntime onnxruntime-directml` and `pip install onnxruntime-directml==1.15.1`
Am I editing the install file and putting it in there or?

**Comment by lysxelapsed** [comment]
Haven't used the installer/miniconda in a long time, so this is as far as I can remember:
 - Open “Anaconda Prompt (miniconda3)” (should be in your Start Menu after install, or just type anaconda in the search field)
 - Head to the harddrive where roop-unleashed is installed ("D:" for example)
 - Head to your roop-unleashed/scripts folder ("cd D:\roop-unleashed\scripts" for example)
 - conda activate
 - pip uninstall onnxruntime onnxruntime-directml
 - pip install onnxruntime-directml==1.15.1

Not sure about the exact "scripts" folder, you can easily look it up yourself.

AMD seems to be tricky in some cases, here's a whole thread about it: #428

**Comment by samrluxford** [comment]
Thanks by doing this I have gotten it to work however it is using the CPU instead of the GPU which isn't a huge problem just that it's slow I read through that thread you linked but I don't get a DML under settings it doesn't have an option for that it just says Cpu when it loads and the other options are cuda and tensort. Even when not set to cpu in provider it still just fully uses cpu. Is there a way to get it to use the gpu?

**Comment by lysxelapsed** [comment]
If you followed the instructions / tipps here and in #428, it's possible your card isn't even supported. What graphics card you got?

**Comment by lysxelapsed** [comment]
RX 6800 XT is more than enough. You could try a manual install, explained here -> #210 (first and last section, ignore the specific commit stuff)
then in the same cmd window after install pip uninstall onnxruntime onnxruntime-directml followed by pip install onnxruntime-directml==1.15.1
thats all I got 🤷‍♂️

**Comment by samrluxford** [comment]
Hi there I tried reinstalling everything manually that didn't work are you able to confirm which scripts folder it is when I cd in
cd D:\roop-unleashed\( Which folder is here after roop-unleashed)
Because I haven't been able to find the specific one before I run the `pip uninstall onnxruntime onnxruntime-directml` and `pip install onnxruntime-directml==1.15.1`?

**Comment by lysxelapsed** [comment]
If you installed it manually, the scripts folder is in the main folder. With the installer I'm not sure, but probably the same. Just open the main folder in explorer and type scripts in the search field in the upper right corner.

This is the approach after manual install:
Open a terminal window in the scripts folder (type cmd and hit enter in the path field):
![scripts](https://github.com/C0untFloyd/roop-unleashed/assets/63816546/87946ddb-8fa5-45f7-ae44-8f6ec77fa300)

Type activate, hit enter. You'll see that the environment is activated:
![activate](https://github.com/C0untFloyd/roop-unleashed/assets/63816546/dee3726d-42be-4a02-b87a-fe37adf8cb42)

Type pip uninstall onnxruntime onnxruntime-directml, hit enter.
Type pip install onnxruntime-directml==1.15.1, hit enter.
Start with python run.py
Make a batch-file and place it in the roop-unleashed main folder (see #210 last part), so you don't have to start manually every time.

It's the same approach after the use of the installer, but you (probably) need to use the anaconda prompt instead of cmd and type conda activate instead of just activate. Install directml, close the anaconda prompt and launch with windows_run.bat.

**Comment by samrluxford** [comment]
Yeah I had it in the right folder it turns out since I couldn't download onnxruntime-directml==1.15.1 it would only let me install onnxruntime-directml==1.17.1 or onnxruntime-directml==1.17.0 I was installing the first I needed to install the second
![Screenshot (5)](https://github.com/C0untFloyd/roop-unleashed/assets/103809204/ef395a2f-85d0-4eee-b84f-af6f1539913f)
It still is just using the CPU though even with dml selected and only one thread?

**Comment by samrluxford** [comment]
I'm checking gpu and cpu usage with AMD software adrenaline edition
![Screenshot (9)](https://github.com/C0untFloyd/roop-unleashed/assets/103809204/81a40832-affe-42ca-9c6b-6dc75fd20c20)
It still says using device:CPU how do I change that if it's not picking up me changing the provider?

**Comment by lysxelapsed** [comment]
nope it's not using dml, it should say "Using provider ['DmlExecutionProvider'] - Device:cpu" instead of "[ ] - Device:cpu"

try the solution in the last post of #70, seems to correlate with your error message (dropdown.py)

**Comment by lysxelapsed** [comment]
Oh.. sorry about that, forgot to mention:
When editing a py-file, you need to delete the already compiled version in the pycache-folder. Otherwise it's gonna use the same old thing from pycache again, without your changes.
Just delete that one and start roop-unleashed again.
And again: don't get confused by the 'device:cpu', it will say that even when it's using dml. Important is the part that comes before, needs to say ['DmlExecutionProvider']

**Comment by samrluxford** [comment]
That has done it, it is working off my GPU now!
Thank you so much for taking the time to help me through this I really appreciate it.

**Comment by lysxelapsed** [comment]
Nice! Glad I could help 😃

**Comment by lysxelapsed** [comment]
Your graphics card isn't suited for these kinds of tasks. Even my old 1660 Super, which is at a staggering 1022% relative performance compared to the Radeon 530, was barely able to run roop-unleashed.
Advice: Graphics card with 6GB VRAM _at the very least_.

**Comment by Alexisback** [comment]
> Your graphics card isn't suited for these kinds of tasks. Even my old 1660 Super, which is at a staggering 1022% relative performance compared to the Radeon 530, was barely able to run roop-unleashed. Advice: Graphics card with 6GB VRAM _at the very least_.

It's a laptop, I can't change the graphics card because it's soldered into the motherboard (I think)

**Comment by spoonsc2** [comment]
Hi! Just piggy backing off the comment above about multiple GPUs. 

I have a 7900xtx, but I'm getting 2fps! (at work so can't provide screencaps etc, only thought to check after this thread) I have setup other SD webuis with Zluda and had to set Hip devices to see my GPU. Is there a similar command line argument for DML? I suspect I'll have to do this. I'm reluctant to turn off my iGPU (on 7800x3d) in case of any dramas. 

offtopic - Zluda support would be insane, love this app great work!
