### ISSUE TITLE
Browser/UI Problems since v3.6.2

### ISSUE THREAD

**Issue by C0untFloyd** [C0untFloyd/roop-unleashed#564]
Currently there are lots of reports with several different browser/UI problems. The reason is me upgrading to a newer [gradio](https://www.gradio.app/guides/quickstart) version, which seems to be quite bug-ridden. Downgrading to the old version is not an option because this would require a downgrade and rewrite of many functions and manual masking would not be possible. I updated the requirements for gradio to 1.24.0 in the hopes that most of the browser issues are fixed by them. Please update roop unleashed, re-install to the new gradio version 1.24.0, test and let me know in this thread!
If it's still not working for you or you encounter that high cpu scenario, also try other browsers like edge, firefox etc.
Personally I never had any of the problems with Firefox.

**Comment by lysxelapsed** [comment]
Argh, sorry gradio (and we 🙈 ) are giving you a hard time again. Will update und report back later today.
And thank you for your hard work, as always 😉

**Comment by kreativezgit** [comment]
I tried a firefox portble without privacy and security setting and it works. Must be a setting that blocks the renderer.

**Comment by lysxelapsed** [comment]
Did some testing with the benchmark video, the 100 test vid and the different enhancers. I still get this one, mostly at the end of processing, sometimes when changing the input face:
`Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen`

And a new one, at the start of processing:
`C:\*****\roop-unleashed\roop\ProcessMgr.py:118: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.options.imagemask is not None and "layers" in self.options.imagemask and len(self.options.imagemask["layers"]) > 0:`

First one does not have any impact on the result or processing speed as far as I can tell.
Second one I'm not really sure. My first impression was "it's maybe a bit more blurry?" - _before_ I opened up ProcessMgr.py to see what the function is about, still not getting it fully - But it could be just my tired eyes.
Oh and the "Processed File(s)" field still doesn't show the progress while processing. But that's insignificant in my opinion, since you can see the progress in the terminal window.
No UI issues on my side with Chrome, but I didn't have them with older versions either. As far as I've seen, most people having UI issues are running it on colab, kaggle or whatever.

Aside from that - and the annoying cpu-at-full-turbo-blast-reencoding for the last file of a batch, so gradio can display it in the result field, but that's not new - I think it runs smoothly 👍 Thanks for the update!

**Comment by Bootwilliam1** [comment]
Hey, im also having problems with Roop Unleashed atm. I'm running from Google Collab. Any ideas on how to fix. I was using it yesterday with no issues 
Cheers

**Comment by Bootwilliam1** [comment]
Like it is completely unusable and straight up doesnt work haha

**Comment by Bootwilliam1** [comment]
also ive tried with, chrome, brave and firefox. Still not working

**Comment by C0untFloyd** [comment]
> First one does not have any impact on the result or processing speed as far as I can tell.

Can't do anything about it. Seems to be gradio innards. Never saw this using Firefox but I'm also rarely swapping videos at all.
 
>Second one I'm not really sure. My first impression was "it's maybe a bit more blurry?" - before I opened up ProcessMgr.py to see what the function is about, still not getting it fully - But it could be just my tired eyes.

It's a test if there's a manual mask (the drawn one) present and if yes, it will be used to mask out the drawn areas. I don't think you're using it and if there's no mask then there is no blending/blurring. 

> and the annoying cpu-at-full-turbo-blast-reencoding for the last file of a batch

Hm, should this be optional? Like a setting checkbox? I could imagine taking this quite long for big videos.

**Comment by lysxelapsed** [comment]
> Can't do anything about it. Seems to be gradio innards. Never saw this using Firefox but I'm also rarely swapping videos at all.

Yeah that was my first thought, too. No biggie at all, since it doesn't have a negative impact.

> It's a test if there's a manual mask (the drawn one) present and if yes, it will be used to mask out the drawn areas. I don't think you're using it and if there's no mask then there is no blending/blurring.

Ah ok, thanks for clarifying. You're right, used masking features only for testing.

> Hm, should this be optional? Like a setting checkbox? I could imagine taking this quite long for big videos.

If it doesn't create too much work, I'd say yes. I've never used the preview in the browser, always went to the output folder directly. But I sure am glad that it pointed out the insane "turbo boost short power max" default value, which was "unlimited" and way too much for air cooling with a 13700k 😄 Even the "normal" turbo boost power max was at 253W TDP 🔥

**Comment by C0untFloyd** [comment]
Added that option now, really makes sense for most videos. I'm also just playing it with VLC from the output folder.

**Comment by lysxelapsed** [comment]
Nice addition. Appreciate it, thx!
Haven't encountered any other issues, running locally on win11 with chrome 👍
