### ISSUE TITLE
"File is not a zip file" error while importing .fsz facesets

### ISSUE THREAD

**Issue by xRoyBx** [C0untFloyd/roop-unleashed#603]
This happens when you have to select .fsz faceset as source, expecially large ones (about 100-200 mb).

The strange thing is that if you try to import a set in zipped format, it doesn't even recognize it :D

**Comment by C0untFloyd** [comment]
You created a faceset of ~200 MB size?!? 😮 
How many faces are in there? That sounds like totally over the top. You'll hardly ever need more than 8 face images of a person. My highest number of images in a faceset is actually 6! Keep in mind, the facial features are averaged for swapping. This means using too many and too different face images (different age, different lighting, different angles) can also very much degrade the facesets. Back to your question: yes, facesets are really zip-files. To have them accepted just change the extension to .fsz

**Comment by isurajboss** [comment]
> You created a faceset of ~200 MB size?!? 😮 How many faces are in there? That sounds like totally over the top. You'll hardly ever need more than 8 face images of a person. My highest number of images in a faceset is actually 6! Keep in mind, the facial features are averaged for swapping. This means using too many and too different face images (different age, different lighting, different angles) can also very much degrade the facesets. Back to your question: yes, facesets are really zip-files. To have them accepted just change the extension to .fsz

change extention to .zip , still its not accepting it

**Comment by Kingkladzemcr** [comment]
> > You created a faceset of ~200 MB size?!? 😮 How many faces are in there? That sounds like totally over the top. You'll hardly ever need more than 8 face images of a person. My highest number of images in a faceset is actually 6! Keep in mind, the facial features are averaged for swapping. This means using too many and too different face images (different age, different lighting, different angles) can also very much degrade the facesets. Back to your question: yes, facesets are really zip-files. To have them accepted just change the extension to .fsz
> 
> same thing is happening with me,, .zip or .fsz both extention file are not working,

**Comment by Kingkladzemcr** [comment]
Yes unfortunately this has now started happening for me also. Started on 7/7/24

**Comment by OneNiNE87** [comment]
Every click at "Create/Update Faceset file" adds the previous number of pirctures plus any new.

**Comment by lapinb** [comment]
I also make mistakes when placing the fsz. The problem is random. This is what I do when it happens to me.
1) The file.fsz file is failing.
2) I rename file.fsz to file.zip
3) I place the contents of file.zip in ‘Face management -> input Files’ (I use Total Commander, I don't need to extract the files. My zip behaves like a normal directory)
4) I click on ‘Create'
5) I recover the new fsz file, which works!
6) I keep the file.zip from point 2. When the problem starts again, that's where I go to look for the files, not in the file.fsz I've just created. I'm afraid that if I export the images too much, they'll deteriorate.
Here's my ‘solution’. I hope it works for you.
