### ISSUE TITLE
"Specify face selection for swapping" returns to default

### ISSUE THREAD

**Issue by RoopUser** [C0untFloyd/roop-unleashed#643]
I'll skip all the preamble, but I recall this select box sticking to what it was on.
When dumping uploaded videos this select option will go back to "First Found".

**Comment by C0untFloyd** [comment]
Yes this is correct and it makes a lot of sense because when you remove your target images/videos, you're also removing your previously selected target faces. Back when I didn't reset this, many people thought faceswapping doesn't work because they still had it on "Selected face" without actually having a face specified.
