### ISSUE TITLE
Batch Processing Bug & Enhancement Only Using CPU Memory

### ISSUE THREAD

**Issue by Freebird0021** [C0untFloyd/roop-unleashed#73]
I wanted to report two issues based on my use of Roop Unleashed that I did not read about from other users:

1) Batch Processing seems to not work for images. For example, if I have 10 pictures in a folder that I want to batch process, when I begin the process, it only works on the FIRST image but not the rest. Please note, I have not tested the batch process option for videos, as I do not trust the program to remain stable for long periods of time.

2) I notice that my GPU (RTX 2060 Super) kicks in about 50% when processing the face swap (10-20 FPS), This is fast. However once the face enhancement process starts, it is MUCH slower (1-2 FPS at best). My theory is that the GPU does NOT kick in during face enhancement (using Codeformer for example) and the CPU does the processing at this phase. Can you please ensure that their is a command in the code to activate GPU during face enhancement? I am a noob at coding, so I will not be much help there.

I just wanted to point these issues out and get feedback. Loving the program so far. I would 100% support a paid (and optimized) version of this, especially once the masking issues and 512x512 face enhancements are rolled out.

**Comment by C0untFloyd** [comment]
1. This is with the main version?
2. Face enhancing IS much, much slower even when using GPU. There is a whole upscale and GAN Network running behind the curtains, which is a lot more sophisticated than just pasting a source face onto a target face. If you specified your GPU it will be used:
[Codeformer getDevice](https://github.com/C0untFloyd/roop-unleashed/blob/main/enhancer/Codeformer.py#L25C40-L25C40)
[Utility getDevice](https://github.com/C0untFloyd/roop-unleashed/blob/main/roop/utilities.py#L155)

I don't think any of the roop original or variant guys (including me) deserve to be paid, because we all just use the supplied inswapper model created by insightface to do the deepfake. And they are sadly also the ones to ask for the 512x512 model, there's nothing we can do about it. Masking I can see progress independant of this, you can already try rough masking in my gradio version or the associated [Colab](https://github.com/C0untFloyd/roop-unleashed/blob/gradio/roop-unleashed.ipynb)
