### ISSUE TITLE
Feature Request: Manual Face Adjustment

### ISSUE THREAD

**Issue by Beliathal** [C0untFloyd/roop-unleashed#866]
The way it's done in [Rope](https://github.com/Hillobar/Rope) is very useful. Often times automatic face alignment fails to find the right proportions/angle of the input face. in Rope it's solvable by Face Adjustment option which allows to manually scale the input face:

![Rope_1](https://github.com/user-attachments/assets/32b1d02b-8918-4a79-b8d0-6d34a4e92390)

It would be very nice to have this option in roop-unleashed :)

**Comment by Beliathal** [comment]
> yea the face offset is nice, but it goes one way only?

It goes both ways, can expand/shrink the face and also change the angle.

**Comment by C0untFloyd** [comment]
I'm not that familiar with Rope, is this for the face you want to paste upon the other or for the original one?
Also, I'm guessing KPS stands for keypoints which would be Eyes,Nose,Mouth positions. Scaling the positions would also scale the face, then why is there an extra slider for the face itself?

My opinion: yes, sometimes the alignment gets things wrong but this happens mostly at extreme angels where the face detection will fail at one point or the other anyway. I'd rather have something to correct single keypoint positions because very often there is 1 eye visibly offset (dropped down) from the other one.
