### ISSUE TITLE
progress bar inside web app 

### ISSUE THREAD

**Issue by Jynkz41** [C0untFloyd/roop-unleashed#911]
Is it possible to add back the progress bar overlay to the processed files section while rendering, it used to be there a long long time ago. It would really help since I use it remotely over my network and don't have access to my console view to monitor my progress. Keep up the awesome work! lots of progress lately !

**Comment by C0untFloyd** [comment]
Believe it or not, it's still the same code as the one where it was previously working! Since it stopped working I debugged it a couple of times only to find out that something basic changed in the inner gradio workings, which prevents the rendering of the progress. I still have hopes that some day the gradio devs will sort out some of the issues with the newer versions but currently there are lots of, take a look yourself https://github.com/gradio-app/gradio/issues
Anyway, I also would love to have the progress display back!

**Comment by C0untFloyd** [comment]
Sorry, I don't have much time lately.
I can tell you it stopped working the moment gradio deprecated the gradio.Update() method for components, many moons ago. There you had to specify the changed property of the component. Now instead you need to return the whole object with the changed property inside.
The relevant line is this:
https://github.com/C0untFloyd/roop-unleashed/blob/f0950c276adaa404392cfed0c33e030c163eb5b4/roop/ProcessMgr.py#L345

And yes it's very convoluted and the progress stuff still is from the original roop over 2 years ago (and they didn't like OOP and used delegates very much).
