### ISSUE TITLE
Extras / enhancers the performance is terribly slow.

### ISSUE THREAD

**Issue by talbertj20** [C0untFloyd/roop-unleashed#945]
When using the extras / enhancers the performance is terribly slow. Previously when using ESRGAN X2 i would process at about 1-2 fps
and now it is about 33 fps. I do not see a drop in face swapping, or at least nothing as noticeable. This has been occurring for  the past several release. See screenshots below for errors.

Things i have tried so far and still get the same results.
-Completely deleted old Roop-Unleashed Folder.
-Completed removed all traces of NVidia Drivers
-Ran Windows 11 Updates
-Reinstalled NVidia CUDA 11.8
-Fresh install of Roop-Unleashed on my fastest local SSD Drive.

Other System Specs:
AMD Ryzen 7 5800X3D
32GB RAM

**To Reproduce**
1. Go to 'Extras'
2. Add Image Files to Process
3. Click on 'Enhancers'
4. Scroll down to 'ESRGAN X2'
5. Click on Start Processing
6. See error in screenshot below

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ X] Windows 11 23H2
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [X ] NVIDIA (NVIDIA GeForce RTX 4070 Ti SUPER OC Edition)
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**
roop unleashed 4.3.2

**Screenshots**
![Screenshot 2024-10-04 092605](https://github.com/user-attachments/assets/a959ec1b-d542-4792-889b-0c7d18987d9e)
![Screenshot 2024-10-04 103223](https://github.com/user-attachments/assets/43c26116-c51d-48f8-acf1-6365eec1577d)

**Comment by C0untFloyd** [comment]
Thanks for the info, I can reproduce the warning in yellow but I'm actually unsure if this wasn't always present. Upscaling always was quite slow with my RTX 2060 Super so I'm not certain if it's slower or faster nowadays. What I'm sure about is that there has been no code change since upscaling was first implemented. There were however upgrades of the onnxruntime versions.
Your powerful gpu taking so long for a frame isn't right. For testing I upscaled a 1920x1080 video with ESRGANx2 and it's taking ~7 secs on average for a frame. Just an idea, you're writing that you installed new and I'm seeing that you're using 3 threads. Perhaps you used a higher number of frames back then? Because as you have quite a fast gpu the number of threads here could make a difference. I'm still investigating in this case, perhaps there is something but you could test if 6 threads make a difference for you.

**Comment by talbertj20** [comment]
I was already using jpg output. I did increase threads from 3 to 6 and restarted roop-unleashed and rana small test.

![image](https://github.com/user-attachments/assets/32e932f0-a870-42df-9d18-7777e9ee7955)

**Comment by jackjack1234321** [comment]
> 이제 여러분이 포스트 프로세싱 대신 업스케일링을 좋아하는 이유를 알았습니다. ` elif self.prev_type == "real_hatgan_x4": model_path = resolve_relative_path('../models/Frame/real_hatgan_x4.onnx') self.scale = 4`
>>>>>
Where should I change the code???
I also had a hard time using it because the speed was too slow, so I tested it with 128px and it was better.
Can you tell me where to add the code???
