### ISSUE TITLE
third time again this error

### ISSUE THREAD

**Issue by papagodzilla** [C0untFloyd/roop-unleashed#986]
any one?
![error roop](https://github.com/user-attachments/assets/225de7a6-ebb3-4117-b4f6-263493728dcd)

**Comment by Zagreus9723** [comment]
I think that this is an issue with your network and tls certificates instead of being an issue with the project. The error is saying that the TLS certificates for hugging face can't be verified. This might be of some help. https://stackoverflow.com/questions/77442172/ssl-certificate-verify-failed-certificate-verify-failed-unable-to-get-local-is

**Comment by papagodzilla** [comment]
nevermind thanks for reply but i have to do it manually and its working now.
